project 'horecafy.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'horecafy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackIT
  pod 'Alamofire', '~> 4.6'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'CarbonKit', '~> 2.1.10’
end
